# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Jobsity Test' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Jobsity Test
    pod 'Alamofire'
    pod 'NVActivityIndicatorView'
    pod 'PagerMenu', :git => "https://github.com/Kaakati/PageMenu.git", :branch => "2.0.1"

end
